version: '3.8'

services:
  # Node.js API service
  wpnova-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - DOWNLOAD_URL=${DOWNLOAD_URL}
    volumes:
      - ./public:/home/node/app/public
    restart: unless-stopped
