version: '3.8'

services:
  # Node.js API service
  wpnova-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - DOWNLOAD_URL=${DOWNLOAD_URL}
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    volumes:
      - ./public:/app/public
    restart: unless-stopped
